<?php
/*
Template Name: [Article Submission]
*/

/***************** DO NOT EDIT THIS FILE *************************
******************************************************************

INFORMATION:
------------

This is a core theme file, you should not need to edit 
this file directly. Code changes maybe lost during updates.

LAST UPDATED: June 26th 2011
EDITED BY: MARK FAIL
------------------------------------------------------------------

******************************************************************/

global $PPTFunction, $PPTDesign, $userdata; get_currentuserinfo(); // grabs the user info and puts into vars

	$wpdb->hide_errors(); nocache_headers();
	
	get_header();
	
	if(isset($_POST['action'])){
	
	
		if(	$_POST['code'] == $_POST['code_value']){
  
			$my_post = array();
			$my_post['post_title'] 			= $_POST['form']['title'];
			$my_post['post_content'] 		= $_POST['form']['description'];
			$my_post['post_excerpt'] 		= $_POST['form']['short'];
			$my_post['post_status'] 		= get_option("display_listing_status");
			$my_post['post_author'] 		= $user_ID;
			$my_post['post_category'] 		= array($_POST['CatSel'][1]);
			$my_post['tags_input'] 			= $_POST['form']['tags'];
			$my_post['post_type']			= "article_type";
			$POSTID 						= wp_insert_post( $my_post );
			
			add_post_meta($POSTID, "hits", "0");
			add_post_meta($POSTID, "featured", "no");
			add_post_meta($POSTID, "short_desc", $_POST['form']['short']);
			add_post_meta($POSTID, "email", $_POST['form']['email']);
			
			$GLOBALS['error'] 		= 1;
			$GLOBALS['error_type'] 	= "success"; //ok,warn,error,info
			$GLOBALS['error_msg'] 	= SPEC($GLOBALS['_LANG']['_tpl_article-add3']);
			
			unset($_POST['form']);
		
		
		}else{

		$GLOBALS['error'] 		= 1;
		$GLOBALS['error_type'] 	= "error"; //ok,warn,error,info
		$GLOBALS['error_msg'] 	= SPEC($GLOBALS['_LANG']['_tpl_contact_error2']);		
 
		}
		
	}	

	/* ================ LOAD TEMPLATE FILE =========================== */	
 
	if(file_exists(str_replace("functions/","",THEME_PATH)."/themes/".get_option('theme')."/_tpl_add-article.php")){
		
		include(str_replace("functions/","",THEME_PATH)."/themes/".get_option('theme').'/_tpl_add-article.php');
		
	}else{ 
	
		include("template_".strtolower(PREMIUMPRESS_SYSTEM)."/_tpl_add-article.php");
	
	}
	
?>